# mypy.ini

[mypy]
# this section is required
# you can add a mypy_path here, if you need one.

# example of explicitly ignoring missing stubs
# for a dependency and its subpackages.
# This is safer than ignoring everything
# with the --ignore-missing-imports option.

[mypy-pyproj.*]
ignore_missing_imports = True
